/**
 * The game registry. One import per launch game; each game's folder exports
 * its Game object as the default export of index.ts. Build tracks replace the
 * stub inside their own folder — they do not edit this file.
 */

import type { AnyGame } from '../kernel/types.ts';
import tictactoe from './tictactoe/index.ts';
import connect_drop from './connect_drop/index.ts';
import chess from './chess/index.ts';
import checkers from './checkers/index.ts';
import reversi from './reversi/index.ts';
import hex from './hex/index.ts';
import nine_mens_morris from './nine_mens_morris/index.ts';
import go from './go/index.ts';
import chinese_checkers from './chinese_checkers/index.ts';
import backgammon from './backgammon/index.ts';
import landlord from './landlord/index.ts';
import islanders from './islanders/index.ts';

export const GAMES: Record<string, AnyGame> = {
  tictactoe,
  connect_drop,
  chess,
  checkers,
  reversi,
  hex,
  nine_mens_morris,
  go,
  chinese_checkers,
  backgammon,
  landlord,
  islanders,
};

export function getGame(id: string): AnyGame | undefined {
  return GAMES[id];
}
