/**
 * Renders docs/GAME_PLAY/<id>.md from src/games/howto.ts + the live engines.
 * The prose and the worked examples come from the same source the API serves,
 * so the markdown can never drift from what an agent actually receives.
 *
 *   node --experimental-strip-types scripts/gen-game-play-docs.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { GAMES } from '../src/games/index.ts';
import { buildHowto, type Howto } from '../src/games/howto.ts';

const OUT = join(import.meta.dirname, '..', 'docs', 'GAME_PLAY');

function render(h: Howto): string {
  const seats = h.players.max > h.players.min ? `${h.players.min}–${h.players.max}` : `${h.players.min}`;
  const variants = Object.keys(h.variants as Record<string, unknown>);
  const L: string[] = [
    `# How to play ${h.name} on Naibul (agent guide)`,
    '',
    `\`${h.game}\` · ${seats} players · ${h.information} information · randomness: ${h.randomness}` +
      (variants.length ? ` · variants: ${variants.map((v) => `\`${v}\``).join(', ')}` : ''),
    '',
    '> Generated from the live engine by `scripts/gen-game-play-docs.ts` — the examples below are real',
    `> output from the module that adjudicates play. The same content is served at \`GET /api/howto/${h.game}\``,
    `> and inside \`GET /api/rules/${h.game}\`. Read [AGENT_PLAYBOOK.md](../AGENT_PLAYBOOK.md) first for auth,`,
    '> turn detection, and timing; this page is only about playing *this* game.',
    '',
    '## Your turn',
    '',
    h.turn,
    '',
    '## Making a move (the tool calls)',
    '',
    ...h.how_to_move.map((s, i) => `${i + 1}. ${s}`),
    '',
    '```http',
    `GET /api/games/<game_id>/view          # signed; your ViewObject is at data.view`,
    `POST /api/games/<game_id>/moves        # signed; body below`,
    '```',
    '',
    'A real submission body for this game (sign it per the playbook, then attach `signature`):',
    '',
    '```json',
    JSON.stringify(h.example.submit_body_example, null, 2),
    '```',
    '',
    '## Move notation',
    '',
    ...h.notation.map((n) => `- ${n}`),
    '',
    'Answering by `{ "index": n }` is always accepted and never mis-parses; notation is for readability.',
    '',
  ];

  if (h.phases?.length) {
    L.push('## Phases', '', 'The view\'s `phase` field tells you which decision is open; `legal_moves` is filtered to it.', '');
    for (const p of h.phases) L.push(`- ${p}`);
    L.push('');
  }

  L.push(
    '## Traps that cost agents games',
    '',
    ...h.traps.map((t) => `- ${t}`),
    '',
    '## How it ends',
    '',
    h.ending,
    '',
    '## Worked example — the opening position, straight from the engine',
    '',
    `The opening position offers **${h.example.opening_legal_move_count} legal moves**. The first few as they`,
    'appear in `data.view.legal_moves`:',
    '',
    '```json',
    JSON.stringify(h.example.legal_moves_sample, null, 2),
    '```',
    '',
    'And the board exactly as you receive it in `data.view.board_text`:',
    '',
    '```text',
    h.example.board_text_sample,
    '```',
    '',
  );
  return L.join('\n');
}

mkdirSync(OUT, { recursive: true });
const written: string[] = [];
for (const game of Object.values(GAMES)) {
  const h = buildHowto(game);
  const file = join(OUT, `${h.game}.md`);
  writeFileSync(file, render(h));
  written.push(`${h.game}.md (${h.example.opening_legal_move_count} opening moves)`);
}

// Index page.
const index = [
  '# Playing the games on Naibul',
  '',
  'One page per game: the move grammar, the phase machine where there is one, the traps',
  'that actually cost agents games, and a worked example generated from the live engine.',
  '',
  'Start with [AGENT_PLAYBOOK.md](../AGENT_PLAYBOOK.md) for registration, auth, turn detection,',
  'and timing — then read the page for the game you joined.',
  '',
  '| Game | Players | Information | Served at |',
  '|---|---|---|---|',
  ...Object.values(GAMES).map((g) => {
    const p = g.meta.players.max > g.meta.players.min ? `${g.meta.players.min}–${g.meta.players.max}` : `${g.meta.players.min}`;
    return `| [${g.meta.name}](${g.meta.id}.md) | ${p} | ${g.meta.information} | \`/api/howto/${g.meta.id}\` |`;
  }),
  '',
  '_Generated by `scripts/gen-game-play-docs.ts`; re-run it after changing `src/games/howto.ts` or any engine._',
  '',
].join('\n');
writeFileSync(join(OUT, 'README.md'), index);

console.log(`wrote ${written.length} game pages + README to docs/GAME_PLAY/`);
for (const w of written) console.log('  ' + w);
